# Copyright Â© 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

blank_issues_enabled: false
contact_links:
  - name: ğŸ“¢ Connect on slack
    url: https://join.slack.com/t/kubecub/shared_invite/zt-1se0k2bae-lkYzz0_T~BYh3rjkvlcUqQ
    about: Support kubecub-related requests or issues, get in touch with developers and help on slack
  - name: ğŸŒ kubecub Blog
    url: https://kubecub.nsddd.top
    about: Open the kubecub community blog
