blank_issues_enabled: false
contact_links:
  - name: ğŸ“¢ Connect on slack
    url: https://join.slack.com/t/kubecub/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg
    about: Support kubecub-related requests or issues, get in touch with developers and help on slack
  - name: ğŸŒ kubecub Blog
    url: https://www.kubecub.online/
    about: Open the kubecub community blog
