# https://github.com/BetaHuhn/repo-file-sync-action
name: Synchronize kubecub public code to other repositories
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.21.0
        with:
          GH_INSTALLATION_TOKEN: "${{ secrets.BOT_GITHUB_TOKEN }}"
          GH_PAT: ${{ secrets.BOT_GITHUB_TOKEN }}
          CONFIG_PATH: .github/sync.yml
          ORIGINAL_MESSAGE: true
          SKIP_PR: true
          COMMIT_EACH_FILE: false
          COMMIT_BODY: "ðŸ¤– kubbot to synchronize the warehouse"
          GIT_EMAIL: "3293172751nss@gmail.com"
          GIT_USERNAME: "kubbot"
          PR_BODY: kubecub provides automated community services
          REVIEWERS: |
            cubxxw
            kubbot
          PR_LABELS: |
            file-sync
            automerge
          ASSIGNEES: |
            kubbot